### PR TITLE
Fix int type bug

### LINKED ISSUE #72: Pickled integer
Int values pickled in RedisCache
In Redis db it looks like hex string `!\x80\x04\x95\x04\x00\x00\x00\x00\x00\x00\x00M\xC2z.`, not `31426`

Environment:

- Python version: 3.8
- CacheLib version: 0.3.0

### PR DESCRIPTION
**Pull request by MyrikLD**
```python
>>> a = 1
>>> t = type(a)
>>> a
1
>>> t
<class 'int'>
>>> isinstance(t, int)
False
>>> type(a) == int
True
```

- fixes #72

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [ ] Add or update relevant docs, in the docs folder and in code.
- [ ] Add an entry in `CHANGES.rst` summarizing the change and linking to the issue.
- [ ] Add `.. versionchanged::` entries in any relevant code docs.
- [x] Run `pre-commit` hooks and fix any issues.
- [x] Run `pytest` and `tox`, no tests failed.

### CODE REVIEW

**Comment by davidism** [comment]
`isinstance(value, int)`

**Comment by MyrikLD** [comment]
> `isinstance(value, int)`

```
isinstance(False, int) == True
```

**Comment by northernSage** [comment]
Hey @MyrikLD, thanks for taking the time to write the PR. While I do understand how if `isinstance(type(value), int)` will never evaluate to `true` since `type(value)` will always return `<class 'type'>`, I'm not sure how this is a bug. Why would we want to "see" serialized values? I can't think of any applications for this off the top of my head, so I wonder if we should just drop the type check and pickle dump everything since this is what `chacelib` has been doingso far.

**Comment by northernSage** [comment]
#147

**Pull request closed without merging**
